// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGXp3WCEY1RYUIIta0BujcgpkD2My9N4',
    appId: '1:256575880713:web:103ed9ad82efb2036cc2d8',
    messagingSenderId: '256575880713',
    projectId: 'sistem-informasi-tempat-403af',
    authDomain: 'sistem-informasi-tempat-403af.firebaseapp.com',
    storageBucket: 'sistem-informasi-tempat-403af.firebasestorage.app',
    measurementId: 'G-N0Y009KT7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJjwGGSAo-fJSGAN_0xQVjW3GZHqNB3Q',
    appId: '1:256575880713:android:20b2d4c3a00a772a6cc2d8',
    messagingSenderId: '256575880713',
    projectId: 'sistem-informasi-tempat-403af',
    storageBucket: 'sistem-informasi-tempat-403af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MyZQ23uEgZ5qqt6lmTUjkodor0Lc0is',
    appId: '1:256575880713:ios:04516b10810e5e4c6cc2d8',
    messagingSenderId: '256575880713',
    projectId: 'sistem-informasi-tempat-403af',
    storageBucket: 'sistem-informasi-tempat-403af.firebasestorage.app',
    iosBundleId: 'com.example.sistemInformasiTempatWisata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_MyZQ23uEgZ5qqt6lmTUjkodor0Lc0is',
    appId: '1:256575880713:ios:04516b10810e5e4c6cc2d8',
    messagingSenderId: '256575880713',
    projectId: 'sistem-informasi-tempat-403af',
    storageBucket: 'sistem-informasi-tempat-403af.firebasestorage.app',
    iosBundleId: 'com.example.sistemInformasiTempatWisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADGXp3WCEY1RYUIIta0BujcgpkD2My9N4',
    appId: '1:256575880713:web:31f3cee2b4022fe96cc2d8',
    messagingSenderId: '256575880713',
    projectId: 'sistem-informasi-tempat-403af',
    authDomain: 'sistem-informasi-tempat-403af.firebaseapp.com',
    storageBucket: 'sistem-informasi-tempat-403af.firebasestorage.app',
    measurementId: 'G-T1E3XJRSZ8',
  );

}